# Generated by Django 4.2 on 2026-01-23 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audit', '0001_initial'),
        ('requirements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='requirements.requirement'),
        ),
    ]
