# Generated by Django 4.2 on 2026-01-23 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='additional_document',
            field=models.FileField(blank=True, help_text='Optional: Upload additional PDF document', null=True, upload_to='documents/'),
        ),
    ]
