# Generated by Django 4.2 on 2026-01-23 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('approvals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='documents/')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('document_type', models.CharField(choices=[('original', 'Original'), ('signed', 'Signed')], max_length=50)),
                ('is_signed', models.BooleanField(default=False)),
                ('approval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='approvals.approval')),
            ],
            options={
                'ordering': ['-uploaded_date'],
            },
        ),
    ]
