# Generated by Django 4.2 on 2026-01-26 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
