# Generated by Django 4.2 on 2026-01-23 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='requirement_type',
            field=models.CharField(choices=[('material', 'Material'), ('service', 'Service')], default='material', max_length=20),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='delivery_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='justification',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
