# Generated by Django 4.2 on 2026-01-26 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0003_requirement_requirement_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('modification_requested', 'Modification Requested'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=25),
        ),
    ]
