# Generated by Django 4.2 on 2026-01-26 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0004_alter_requirement_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='last_modified_date',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last modification submission', null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='was_modified',
            field=models.BooleanField(default=False, help_text='Tracks if requirement was modified after approval request'),
        ),
    ]
