# Generated by Django 4.2 on 2026-02-03 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0005_requirement_last_modified_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='attachment',
            field=models.FileField(blank=True, help_text='Optional document attachment', null=True, upload_to='requirements/'),
        ),
    ]
