# Generated by Django 4.2 on 2026-02-03 10:40

from django.db import migrations


def populate_initial_choices(apps, schema_editor):
    DepartmentChoice = apps.get_model('requirements', 'DepartmentChoice')
    RequirementTypeChoice = apps.get_model('requirements', 'RequirementTypeChoice')
    
    # Populate initial department choices
    departments = [
        ('finance', 'Finance'),
        ('marketing', 'Marketing'),
        ('sales', 'Sales'),
        ('technical', 'Technical'),
        ('executive', 'Executive'),
    ]
    
    for value, display_name in departments:
        DepartmentChoice.objects.create(value=value, display_name=display_name)
    
    # Populate initial requirement type choices
    requirement_types = [
        ('material', 'Material'),
        ('service', 'Service'),
    ]
    
    for value, display_name in requirement_types:
        RequirementTypeChoice.objects.create(value=value, display_name=display_name)


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0007_departmentchoice_requirementtypechoice'),
    ]

    operations = [
        migrations.RunPython(populate_initial_choices),
    ]
