# Generated by Django 4.2 on 2026-02-10 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0008_populate_initial_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirement',
            name='delivery_address',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='estimated_cost',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='quotation_deadline',
        ),
        migrations.AlterField(
            model_name='requirement',
            name='requirement_type',
            field=models.CharField(choices=[('general', 'General'), ('capex', 'Capex'), ('quotation', 'Quotation'), ('it_sap', 'IT or SAP'), ('advance', 'Advance')], default='general', max_length=20),
        ),
    ]
